### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Lalna-Rocks** [Topinambur223606/PixelPlanetTools#13]
When my friend was using the bot it started giving out the error for a slow connection.  They ran a speed test and no issues.  The bot was restarted multiple times and the page was reloaded as well.  Is there a fix to this or is it a glitch?

**Comment by Topinambur223606** [comment]
Firstly, try downloading bot again (or building it by yourself). There is a huge change that it will solve an issue because some problems may occur with previous builds.

If problem remains, please attach corresponding logs.
Logs are located by default in `%appdata%\PixelPlanetTools\logs\PixelPlanetBot`.
Every log file contains launch time in filename and launch parameters inside file.

**Comment by Topinambur223606** [comment]
I am closing this issue.
Please reopen and provide details if problem still appears
