### ISSUE TITLE
Bot doesn't work on custom pixelplanet server

### ISSUE THREAD

**Issue by genabetov** [Topinambur223606/PixelPlanetTools#26]
There is no error if I start bot with original server setting

```
C:\Users\xxx\Desktop\pptools>PixelPlanetBot run -x 266 -y 323 -d -i ua.png --serverUrl any.pixelplanet.custom.server
15:43:20.467  [TECHSTATE]     Downloading image...
15:43:20.777  [TECHINFO]      Image is downloaded
15:43:20.777  [TECHSTATE]     Converting image...
15:43:20.830  [TECHINFO]      Image is converted
15:43:20.835  [TECHSTATE]     Calculating pixel placing order...
15:43:21.079  [TECHINFO]      Pixel placing order is calculated
15:43:21.091  [TECHSTATE]     Calculating list of chunks...
15:43:21.311  [TECHINFO]      Chunk list is calculated
15:43:21.382  [TECHSTATE]     Connecting via websocket...
15:43:21.802  [TECHINFO]      Listening for changes via websocket
15:43:21.843  [TECHSTATE]     Downloading chunk data...
15:43:22.706  [TECHINFO]      Chunk data is downloaded
15:43:22.830  [PIXELFAIL]     Failed to place pixel: invalid x coordinate
15:43:22.918  [INFO]          Exiting...
15:43:22.918  [INFO]          Logs were saved to C:\Users\xxx\AppData\Roaming\PixelPlanetTools\logs\PixelPlanetBot\2020-09-25_15-43-20_f83a63e6d0f14cadb543b191dfdd2e3a.log
```

**Comment by Topinambur223606** [comment]
Error code is returned from server.
Also, bot places pixels at default (zero) canvas.
Therefore, there is a few possible causes.

- First one: server is misconfigured and default canvas is too small.
To check it, please ensure that issue is still reproducible and provide the response of `/api/me` endpoint (for example, it is https://pixelplanet.fun/api/me at original PixelPlanet server). Value that indicates the size is `response.canvases[0].size`.
- Second: some other issues at server. Does browser version work fine?
- Third: incorrect bot behavior.
Please provide log file (path is stated in the last log line you provided) to check it if applicable.

**Comment by Topinambur223606** [comment]
Hello @genabetov ,
Is the issue still relevant?

**Comment by Topinambur223606** [comment]
I suggest that the issue is no longer relevant.
Please create a new one if it is reproducible and not first nor second case I mentioned are the cause.
