### ISSUE TITLE
How use proxy?

### ISSUE THREAD

**Issue by DarksliYT** [Topinambur223606/PixelPlanetTools#28]
i place my ip and port and this not connect ._.

**Comment by Topinambur223606** [comment]
Hello,
Please check readme at the main repo page. You can find example there.
If it does not help, please provide the command you use for launching bot.

**Comment by Topinambur223606** [comment]
This issue seems to be irrelevant and "dead", so I will close it.
Please open a new one if bot fails to use proxy.

**Comment by nautics889** [comment]
I'm really sorry for haven't responded for so long. 
I've just checked the latest release with some free proxy, it looks like everything went well. At least bot recognized proxy and failed since it's a free one. 
Nevermind, guess I would manage to test full flow this weekend.
Thank you a lot for resolving this issue, it was really crucial.
